apiVersion: 1

datasources:
  - name: NEA-TimescaleDB
    type: postgres
    uid: nea_tsdb
    url: timescaledb:5432
    user: nea_user
    secureJsonData:
      password: nea_secure_pass
    jsonData:
      database: nea_ami
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: true
    isDefault: true
    editable: true
